#!/usr/bin/env bash
# Installs and configures a haproxy

# upadate local repository indices
sudo apt -y update;

# Install haproxy
sudo apt-get -y install --no-install-recommends software-properties-common;
sudo add-apt-repository -y ppa:vbernat/haproxy-2.9;

sudo apt-get -y install haproxy=2.9.\*;

# add configurations frontend and backend
echo -e "frontend holland-frontend
\tbind *:80
\tmode http
\tdefault_backend holland_backend

backend holland_backend
\tbalance roundrobin
\tserver web-01 54.146.70.249:80 check
\tserver web-02 52.87.220.33:80 check">> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | tee -a /etc/default/haproxy

sudo service haproxy restart
