#!/usr/bin/env bash
# Creates a file containing its PID

trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love me?!; exit 0" SIGINT
trap "rm /var/run/myscript.pid" SIGQUIT || SIGTERM
echo $$> "/var/run/myscript.pid"
while true
do
echo "To infinity and beyond"
sleep 2
done
