#!/usr/bin/env bash
# Displays 'bad luck' for the 4th iteration
#	'good luck' for the 8th iteration
#	'Best Shool' for other iterations

i=1
while [ $i -le 10 ]
do
	if [ $i == 4 ]; then
		echo "bad luck"
	elif [ $i == 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
