#!/usr/bin/env bash
# Prints hours and minutes

hours=0
#minutes=1

while [ $hours -le 12 ]
do
	min=1
	echo "Hour: $hours"
	while [ $min -le 59 ]
	do
		echo $min
		((min++))
	done
	((hours++))
done

#while [ $minutes -le 59 ]
#do
#	sec=1
#	echo "Minute: $minutes"
#	while [ $sec -le 59 ]
#	do
#		echo $sec
#		((sec++))
#	done
#	((minutes++))
#done	
